apply plugin: 'com.android.application'
android {
    namespace "diewland.screen.off"
    compileSdkVersion 34
    defaultConfig {
        applicationId "diewland.screen.off"
        minSdkVersion 16
        targetSdkVersion 35
        versionCode 25
        versionName '2.5'
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }
    productFlavors {
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
}